name: publish-package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: install-moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: post install
        run: |
          moon version --all
          moon update

      - name: prepublish check
        run: |
          moon check
          moon test

      - name: publish
        env:
          SECRET: ${{ secrets.MOONCAKES_TOKEN }}
        shell: bash
        run: |
          if [ -z "$SECRET" ]; then
            echo "Error: MOONCAKES_TOKEN secret is not set."
            exit 1
          fi
          echo "$SECRET" > ~/.moon/credentials.json
          moon publish
          rm ~/.moon/credentials.json
